version: "3.8"

services:
  backend:
    depends_on:
      - db
    build: ./liver_puncture_backend
    volumes:
      - /home/dell/docker-volumns/liver_puncture/static:/app/static
      - /home/dell/docker-volumns/liver_puncture/media:/app/media
      - /home/dell/docker-volumns/liver_puncture/mysqlbackup:/app/backup_mysql
    restart: always
    # privileged: true

    command: ./entrypoint.sh
  nginx:
    depends_on:
      - backend
    build: ./nginx
    volumes:
      - /home/dell/docker-volumns/liver_puncture/static:/static
    restart: always
    ports:
      - 8073:80

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    # image: mysql:5.6
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: "liver_puncture"
      MYSQL_ROOT_PASSWORD: pcl123456
    volumes:
      - /home/dell/docker-volumns/liver_puncture/db-data:/var/lib/mysql
    # command:
    #   [
    #     "mysqld",
    #     "--character-set-server=utf8mb4",
    #     "--collation-server=utf8mb4_unicode_ci",
    #     "--default-authentication-plugin=mysql_native_password",
    #   ]
  adminer:
    image: adminer
    restart: always
    ports:
      - 8086:8080

